site_name: carry's blog
theme:
  name: material
  icon:
    edit: material/pencil
  features:
    - content.action.edit
    - navigation.tracking
    - navigation.expand
    - navigation.top
    - navigation.footer
  font:
    code: JetBrains Mono
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
nav:
 - 首页: index.md
 - new_star_writeup: new_star_writeup.md
